[package]
name = "rkik"
version = "0.2.0"
edition = "2024"
description = "Rusty Klock Inspection Kit - NTP Query and Compare Tool"
[dependencies]
rsntp = "4.0.0"
clap = { version = "4.5", features = ["derive"] }
chrono = "0.4"
console = "0.15"
serde_json = "1.0.140"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"